### ISSUE TITLE
I can't find .sdir files in the game Nintendo Puzzle Collection

### ISSUE THREAD

**Issue by GuckTubeYT** [Nisto/musyx-extract#5]
hello, i want to ripping gamecube song games, and when i check it, its .samp, but i dont get the .sdir
name game: nintendo puzzle collection

**Comment by Nisto** [comment]
@GuckTubeYT I've begun looking into this game. The .sdir data appears to be in the ".rel" files. I will work on this in the coming couple of days and see what I can do. Keep an eye out on https://github.com/Nisto/extractors

**Comment by Nisto** [comment]
It's been taking a bit longer than I hoped, but here's what I know so far...

The music loading process may be working somewhat differently for the different sub-games. Some have .bin files, others seemingly don't, or possibly embed them in the executable (REL/PLF/ELF) files. For arguments sake, I will use the "ycookie" files as example.

At the start of ycookie.bin, there's a table of 32-bit integers. I haven't figured out how they're coded, but it seems like they could be packed with flags, IDs, and offsets/sizes (divided by 1024?), or something along those lines.

**The ycookie.bin file contains both .sdir and .samp data. The first .sdir file is located at 0x2600 and is 0x1400 bytes in size. The .samp data begins at 0x41F20** (not sure of the exact size, but if you extract everything from that offset until the end of ycookie.bin, MusyXExtract will extract it fine).

That's it for now. Been a bit short of time today, so just haven't looked much deeper into my latest finds yet. Just a matter of time..

**Comment by Nisto** [comment]
@GuckTubeYT  I have just posted an extractor in my [Nisto/extractors](https://github.com/Nisto/extractors/blob/master/nintendo_puzzle_collection_musyx.py) repo. As mentioned before, this definitely was more complicated than I had hoped, hence the delay.

To give everyone an idea of just how scattered the data/metadata is between these games, I compiled this table:

| Game / File  | No. songs | No. song-names | No. groups | No. group-names |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ycookie.rel  | 0  | 30 (\*)  | 0  | 3 (\*) |
| ycookie.plf | 0 | 26 (\*) | 0 | 2 (\*) |
| ycookie.bin | 26 | 0 | 3 | 0  |
| |
| dr_mario.rel | 46 | 0 | 1 | 0  |
| dr_mario.plf | 46 | 24 | 1 | 0  |
| |
| panepon.rel | 59 | 0 | 2 | 0  |
| panepon.plf | 59 | 59 | 1 | 0  |
| |
| menu.plf | 2 | 1 | 1 | 0 |
| menu_relsamp.bin | 9 | 0 | 6 | 0 |

**(\*)** Generic names like "grp00" and "sng00", also without direct references to corresponding data as far as I can tell? Seems to be remnant filenames from source compilation stages?

On top of everything, the game has executables with debug symbols in addition to release-binaries, so some things in release-binaries could be manually matched up to track titles purely with the help of CRCs/offsets/sizes of debug-release counterparts. And so I did. That, and menu/dr_mario had duped .song files in the executable data, which I weeded out too.

In the case of Dr. Mario and Panel de Pon, track titles come from variable names in pure code (songs are defined as pure data arrays). However, as you may see from the table provided above, Yoshi's Cookie has no real track titles, and the data is in a separate file (ycookie.bin).

As a result of this inconsistent mess, offsets, sizes and filenames are simply hard-coded into the extractor. In addition to simplifying the extraction process quite a bit, this should also provide more complete coverage/metadata.

**Comment by GuckTubeYT** [comment]
Thanks, sir! I'll try it later
